---
title: 'STAT 443: Lab 10'
author: 'Aronn Grant Laurel (21232475)'
date: "21 Mar, 2025"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(knitr)
library(tseries)
library(forecast)
```

### Question 1

(a)

```{r, echo=TRUE}
freq <- seq(0, 0.5, length.out = 100)

spectral_density <- rep(1/(2*pi), length(freq))

plot(freq,
     spectral_density, 
     xlab = "Frequency (cycles per unit time)", 
     ylab = "Spectral Density", 
     main = "Spectral Density Function for White Noise",
     type = "l")
```


(b)

```{r, echo=TRUE}
q1b <- arima.sim(model = list(order = c(0, 0, 0)), n = 100, sd = 1)

spec.pgram(q1b, 
           log = "no",
           main = "Periodogram of White Noise (n = 100)")
# True Value
abline(h =  1/(2*pi), col = "red", lty = 2)
```

We do not observe any pattern with the fluctuations and it having several frequencies that is
at the true value. While some frequency components show much higher power than the true
value, others show lower power than the true value.

(c)

```{r, echo=TRUE}
q1b <- arima.sim(model = list(order = c(0, 0, 0)), n = 1000, sd = 1)

spec.pgram(q1b, 
           log = "no",
           main = "Periodogram of White Noise (n = 1000)")
# True Value
abline(h =  1/(2*pi), col = "red", lty = 2)
```


(d)

```{r, echo=TRUE}

```


### Question 2

(a)

```{r, echo=TRUE}

```


(b)

```{r, echo=TRUE}

```

(c)

```{r, echo=TRUE}

```


(d)

```{r, echo=TRUE}

```


### Question 3

(a)

```{r, echo=TRUE}

```


(b)

```{r, echo=TRUE}

```

(c)

```{r, echo=TRUE}

```


(d)

```{r, echo=TRUE}

```
