---
title: 'STAT 443: Lab 9'
author: 'Aronn Grant Laurel (21232475)'
date: "14 March, 2025"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#if you do not have the package, type install.packages("name_of_the_package")
library(knitr)
library(tseries)
library(forecast)
```

### Question 1

```{r, echo=TRUE}
# this is where your R code goes
data(LakeHuron)

data.ts.train <- window(LakeHuron,
                     start = c(1875),
                     end = c(1969))

data.ts.test <- window(LakeHuron,
                    start = c(1970),
                    end = c(1972))

plot(data.ts.train,
     main = "Annual Level of Lake Huron",
     xlab = "Time (Year)", ylab = "Annual Lake (ft)")

acf(data.ts.train, main = "ACF of Annual lake Huron")

pacf(data.ts.train, main = "PACF of Annual lake Huron")
```
Since we see an exponential decay in our ACF plot and
a cut off at lag = 2 for our PACF plot, I believe an 
appropriate ARMA model would be an AR(2) process.


### Question 2

```{r, echo=TRUE}
# this is where your R code goes
```


### Question 3

```{r, echo=TRUE}
# this is where your R code goes
```

### Question 4

```{r, echo=TRUE}
# this is where your R code goes
```

### Question 5

```{r, echo=TRUE}
# this is where your R code goes
```

